[package]
name = "hyper_serde"
version = "0.2.0"
authors = ["Anthony Ramine <n.oxyde@gmail.com>"]
description = "Serde support for Hyper types"
license = "MIT"
repository = "https://github.com/nox/hyper_serde"
documentation = "https://docs.rs/hyper_serde"

[lib]
doctest = false

[dependencies]
cookie = {version = "0.4", default-features = false}
hyper = {version = "0.9", default-features = false}
mime = "0.2"
serde = "0.9"

[dev-dependencies]
serde_test = "0.9"
